### ISSUE TITLE
Repository not signed.

### ISSUE THREAD

**Issue by Jorricks** [tproenca/pmsarm7#8]
Hello,

You provided an awesome project however it is very insecure.
This is because your repository is not signed.
The packages can therefore not be authenticated and the computer is vulnerable to a MITM attack.
Would you mind to try to make it signed :)?

**Comment by lorenzschmid** [comment]
I'm not sure if it is wise to post a workaround but if you are aware of what you are doing: Add `[trusted=yes]` in front of the package URL in the source list, i.e.

    echo "deb [trusted=yes] http://dl.bintray.com/tproenca/pmsarm7 jessie main" | sudo tee /etc/apt/sources.list.d/pms.list

For more details see [this answer](https://unix.stackexchange.com/questions/198000/bypass-gpg-signature-checks-only-for-a-single-repository#answer-198454).

**Comment by tproenca** [comment]
Actually, the repository supports`https`. I just changed the documentation.
